### ISSUE TITLE
Object doesn

### ISSUE THREAD

**Issue by ridhvi** [pykih/PykCharts.js#13]

**Comment by ridhvi** [comment]
Hello,

First of all I would like to thank you for the awesome client side charts where I feel it meets most of the requirements.
I am doing a poc and I could create a "pie" chart. Problem comes with the "bar" charts.
I tried both "Column" and "Bar" charts which works fine with the Chrome, but not with the IE. The chart doesn't shows up with the issue "Object doesn't support property or method '_domainBandwidth'". 

For the same "Bar" charts, If I run with the JSON data instead of remote CSV provided in the example, the chart doesn't appear at all. this is all happening with IE browser version 11.

Summarizing the findings
1.  Object doesn't support property or method '_domainBandwidth' exception with the remote CSV data
2. Chart doesn't renders if the data is in JSON format.
Below is the screen shot.

![graph](https://cloud.githubusercontent.com/assets/12256233/8500516/87fb6612-21ba-11e5-8837-dda0803e18ed.jpg)

**Comment by ronakrrb** [comment]
Hello Ridhvi,

We apologize for the inconvenience. Let us look into the issue and comeback with the solution.

**Comment by ronakrrb** [comment]
Hello Ridhvi,

Can you please email us your code and the data file?

**Comment by ridhvi** [comment]
Hello Ronak Bhandari,

Please find the below code.

<script type="text/javascript" src="../Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="../Scripts/pykcharts/pykcharts.1.1.0.min.js"></script>
    <link href="../Scripts/pykcharts/pykcharts.1.1.0.min.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {

            window.PykChartsInit = function (e) {
                var k = new PykCharts.oneD.pie({

                    //Chart Container Id
                    "selector": "#pie_chart",

                    //Data file path
                    //"data": "https://s3-ap-southeast-1.amazonaws.com/chartstore.io-data/pie.csv",
                    "data": [
                        { "name": "Product 1", "weight": 4800 },
                        { "name": "Product 2", "weight": 4000 },
                        { "name": "Product 3", "weight": 2500 }
                    ],
                    //Chart mode
                    "mode": "default",

                    //Chart Size Parameters
                    "chart_width": 620,
                    "chart_height": 400,

                    //Pie parameters
                    "pie_radius_percent": 70,

                    //Chart color parameter
                    "color_mode": "shade",
                    "shade_color": "#255AEE",
                    "chart_color": [
                      "#255AEE"
                    ],

                    //Chart pointer parameters
                    "pointer_overflow_enable": "yes",
                    "pointer_thickness": 1,
                    "pointer_family": "Helvetica Neue,Helvetica,Arial,sans-serif",
                    "pointer_size": 13,
                    "pointer_weight": "normal",

                    //Chart highlight parameters
                    "highlight": "Product 1",
                    "highlight_color": "#08306b",

                    //Chart labels parameters
                    "label_size": 13,
                    "label_weight": "normal",
                    "label_family": "Helvetica Neue,Helvetica,Arial,sans-serif",

                    //Realtime data parameters
                    "real_time_charts_last_updated_at_enable": "no",
                    "real_time_charts_refresh_frequency": 0,

                    //Chart border parameters
                    "border_between_chart_elements_thickness": 1,
                    "border_between_chart_elements_style": "solid",

                    //Clubdata parameters
                    "clubdata_enable": "yes",
                    "clubdata_text": "Others",
                    "clubdata_maximum_nodes": 5,

                    //Chart-interactive parameters
                    "chart_onhover_highlight_enable": "yes",
                    "tooltip_enable": "yes",
                    "transition_duration": 0,
                    //Chart title parameters
                    //"title_text": "Enter title here",
                    "title_size": 2,
                    "title_weight": "bold",
                    "title_family": "Helvetica Neue,Helvetica,Arial,sans-serif",
                    "title_color": "#1D1D1D",

                    //Chart subtitle parameters
                    //"subtitle_text": "Enter subtitle here",
                    "subtitle_size": 1,
                    "subtitle_weight": "normal",
                    "subtitle_family": "Helvetica Neue,Helvetica,Arial,sans-serif",
                    "subtitle_color": "black",

                    //Credits parameters
                    "credit_my_site_name": "PieChart",
                    "credit_my_site_url": ""
                });
                k.execute();



                //var j = new PykCharts.multiD.column({
                //    "selector": "#bar_chart",
                //    "data": "https://s3-ap-southeast-1.amazonaws.com/chartstore.io-data/column.csv",
                //    //"data": [
                //    //    { "x": "January", "y": 48.9, "group": "Rainfall(mm)" },
                //    //    { "x": "Feb", "y": 38.8, "group": "Rainfall(mm)" },
                //    //    { "x": "March", "y": 39.3, "group": "Rainfall(mm)" },
                //    //    { "x": "April", "y": 41.4, "group": "Rainfall(mm)" },
                //    //    { "x": "June", "y": 47, "group": "Rainfall(mm)" },
                //    //    { "x": "July", "y": 48.3, "group": "Rainfall(mm)" },
                //    //    { "x": "August", "y": 59, "group": "Rainfall(mm)" },
                //    //    { "x": "September", "y": 59.6, "group": "Rainfall(mm)" },
                //    //    { "x": "October", "y": 52.4, "group": "Rainfall(mm)" }
                //    //],
                //    "chart_width": 620,
                //    "chart_height": 400,
                //    "background_color": "#FFFFFF",
                //    "mode": "default",
                //    "color_mode": "saturation",
                //    "saturation_color": "#255AEE",
                //    "chart_color": [
                //              "#255AEE"
                //    ],
                //    "axis_onhover_highlight_enable": "no",
                //    "axis_x_enable": "yes",
                //    "axis_x_title": "",
                //    "axis_x_position": "bottom",
                //    "axis_x_pointer_position": "bottom",
                //    "axis_x_line_color": "#1D1D1D",
                //    "axis_x_pointer_size": 12,
                //    "axis_x_pointer_color": "#1D1D1D",
                //    "axis_y_enable": "yes",
                //    "axis_y_title": "",
                //    "axis_y_position": "left",
                //    "axis_y_pointer_position": "left",
                //    "axis_y_line_color": "#1D1D1D",
                //    "axis_y_pointer_size": 12,
                //    "axis_y_pointer_color": "#1D1D1D",
                //    "axis_y_no_of_axis_value": 5,
                //    "axis_y_pointer_padding": 6,
                //    "axis_y_pointer_values": [],
                //    "axis_y_outer_pointer_length": 0,
                //    "axis_y_time_value_datatype": "",
                //    "axis_y_time_value_interval": 0,
                //    //"highlight": "Feb",
                //    "real_time_charts_last_updated_at_enable": "no",
                //    "real_time_charts_refresh_frequency": 0,
                //    "transition_duration": 0,
                //    "border_between_chart_elements_thickness": 1,
                //    "border_between_chart_elements_style": "solid",
                //    "chart_margin_left": 50,
                //    "chart_margin_right": 25,
                //    "chart_margin_top": 35,
                //    "chart_margin_bottom": 35,
                //    "chart_onhover_highlight_enable": "yes",
                //    "tooltip_enable": "yes",
                //    "title_text": "Enter title here",
                //    "title_size": 2,
                //    "title_weight": "bold",
                //    "title_family": "Helvetica Neue,Helvetica,Arial,sans-serif",
                //    "title_color": "#1D1D1D",
                //    "subtitle_text": "Enter subtitle here",
                //    "subtitle_size": 1,
                //    "subtitle_weight": "normal",
                //    "subtitle_family": "Helvetica Neue,Helvetica,Arial,sans-serif",
                //    "subtitle_color": "black",
                //    "credit_my_site_name": "ChartStore.io",
                //    "credit_my_site_url": "https://chartstore.io",
                //    "map_code": "world"
                //});
                //j.execute();

                var j = new PykCharts.multiD.bar({
                    selector: "#bar_chart",
                    data: "https://s3-ap-southeast-1.amazonaws.com/chartstore.io-data/bar.csv",

                    // optional
                    chart_height: 380,
                    chart_margin_left: 150,
                    chart_margin_right: 20
                });
                j.execute();

            }
        });
    </script>



HTML

 <div style="width: 100%">
        <div style="width: 50%; float: left" id="pie_chart"></div>
        <div style="width: 50%; float: right" id="bar_chart"></div>
    </div>


for the pykcharts.1.1.0.min.js and  pykcharts.1.1.0.min.css, I have downloaded from the http://pykcharts.com/ and referenced it.

Let me know if you need any information further.

**Comment by ronakrrb** [comment]
Hello Ridhvi,

This issue was encountered in the one of the previous version and had been fixed in the later version. You may trying downloading the latest version. Also, we have emailed an example working code to you at ridhvi@live.com

**Comment by ridhvi** [comment]
Hello Ronak Bhandari,

I have tried with the attachments that you have sent. I am still facing the issue. It works fine in the local folder but when I try to integrate within SharePoint context, the issue with Bar chart prevails. Any idea what is causing this issue.

**Comment by ronakrrb** [comment]
Hello Ridhvi,

Currently, we are working on a deployment and will be free by 15th. We will look into the issue then. Apologize for the delay.
